title: "Genre Fusion via Activation Steering"
description: "Demo Page"
theme: jekyll-theme-slate

# Customization
markdown: kramdown
highlighter: rouge

# Metadata
author:
  name: "Genre Fusion via Activation Steering"