title: "Fine Grained Music Control"
description: "Fine Grained Music Control demo page"
theme: jekyll-theme-slate

# Customization
markdown: kramdown
highlighter: rouge

# Metadata
author:
  name: "Fine Grained Music Control"